/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShopImport } from './routes/shop'
import { Route as PlayImport } from './routes/play'
import { Route as MeImport } from './routes/me'
import { Route as LeaderboardImport } from './routes/leaderboard'
import { Route as IndexImport } from './routes/index'
import { Route as PlayGameIdImport } from './routes/play.$gameId'

// Create/Update Routes

const ShopRoute = ShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRoute,
} as any)

const PlayRoute = PlayImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRoute,
} as any)

const MeRoute = MeImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRoute,
} as any)

const LeaderboardRoute = LeaderboardImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayGameIdRoute = PlayGameIdImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => PlayRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardImport
      parentRoute: typeof rootRoute
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeImport
      parentRoute: typeof rootRoute
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayImport
      parentRoute: typeof rootRoute
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopImport
      parentRoute: typeof rootRoute
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdImport
      parentRoute: typeof PlayImport
    }
  }
}

// Create and export the route tree

interface PlayRouteChildren {
  PlayGameIdRoute: typeof PlayGameIdRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayGameIdRoute: PlayGameIdRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof MeRoute
  '/play': typeof PlayRouteWithChildren
  '/shop': typeof ShopRoute
  '/play/$gameId': typeof PlayGameIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof MeRoute
  '/play': typeof PlayRouteWithChildren
  '/shop': typeof ShopRoute
  '/play/$gameId': typeof PlayGameIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof MeRoute
  '/play': typeof PlayRouteWithChildren
  '/shop': typeof ShopRoute
  '/play/$gameId': typeof PlayGameIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leaderboard' | '/me' | '/play' | '/shop' | '/play/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leaderboard' | '/me' | '/play' | '/shop' | '/play/$gameId'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/me'
    | '/play'
    | '/shop'
    | '/play/$gameId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MeRoute: typeof MeRoute
  PlayRoute: typeof PlayRouteWithChildren
  ShopRoute: typeof ShopRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  MeRoute: MeRoute,
  PlayRoute: PlayRouteWithChildren,
  ShopRoute: ShopRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/leaderboard",
        "/me",
        "/play",
        "/shop"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/leaderboard": {
      "filePath": "leaderboard.tsx"
    },
    "/me": {
      "filePath": "me.tsx"
    },
    "/play": {
      "filePath": "play.tsx",
      "children": [
        "/play/$gameId"
      ]
    },
    "/shop": {
      "filePath": "shop.tsx"
    },
    "/play/$gameId": {
      "filePath": "play.$gameId.tsx",
      "parent": "/play"
    }
  }
}
ROUTE_MANIFEST_END */
